### ISSUE TITLE
integration/monai/examples/spleen_ct_segmentation_local[BUG]

### ISSUE THREAD

**Issue by Frenz86** [NVIDIA/NVFlare#1885]
**Describe the bug**
I follow the instructions (very clear, thank for this tutorial) but when I submit the job, ./submit_job.sh job
after some seconds, got this erorr:
TypeError: MonaiAlgo.__init__() got an unexpected keyword argument 'train_args'

I have install all requirements, cuda is working properly, but I have only 16GB of RAM and 4GB of GPU.
Do you think is an hardware related fault?

**Desktop (please complete the following information):**
 - OS: [WSL2 -ubuntu22.04]
 - Python Version [e.g. 3.10]
 - NVFlare Version [e.g. 2.3]

Many thanks
Best regards

Frenz

**Comment by holgerroth** [comment]
Hi @Frenz86, this looks like a version conflict. The `train_args` argument has been in MONAI since version 1.2. Please see the requirements for the example [here](https://github.com/NVIDIA/NVFlare/blob/0b4a4915879f54e625d27fc952ca88bdb507aeac/integration/monai/examples/spleen_ct_segmentation_local/requirements.txt#L5). We recommend setting up a virtual environment to avoid conflicts between other installed packages. See instructions [here](https://github.com/NVIDIA/NVFlare/blob/main/examples/README.md#set-up-a-virtual-environment).

**Comment by holgerroth** [comment]
Note, you might run out of GPU memory later once training starts. Memory consumption can be reduced by changing lowering the roi sizes and batch sizes in train.json inside the downloaded monai bundle.
