### ISSUE TITLE
Admin client goes out of sync with server and clients

### ISSUE THREAD

**Issue by vkullu** [NVIDIA/NVFlare#189]
I noticed if I let the server, client and admin console stay idle for a while (say I am done with a round of training and testing) and let the terminal windows just be idle (or my mac goes in idle mode), after a while shutdown all does not work.

Below is the error message

<img width="611" alt="Screen Shot 2022-02-08 at 10 12 33 AM" src="https://user-images.githubusercontent.com/6581358/153050451-7427eee1-9fee-48e0-be34-4de642aa8949.png">

This makes it hard to kill the process. I am still able to shutdown the client and server manually using the stop_fl.sh script but this ghost process remains.

**Comment by vkullu** [comment]
Workaround is 
1. Ctrl+D out of the admin console. 
2. Use stop_fl.sh scripts to stop server and clients a
3. Restart the client and the server
4. Restart the admin

**Comment by yhwen** [comment]
This is because the admin client is timeout and become "not authenticated". You can issue "bye" command to quit the admin, then re-connect again, then use the "shutdown all" command to shutdown the system.

However, we should enhance the admin to automatic quit / logout the admin client after this timeout.

**Comment by YuanTingHsieh** [comment]
Close the issue since it is answered.
I open another issue to track the enhancement.
