### ISSUE TITLE
[BUG]TypeError: Can't instantiate abstract class FedXGBHistogramExecutor with abstract method load_data

### ISSUE THREAD

**Issue by yizhihenpidehou** [NVIDIA/NVFlare#1928]
**Describe the bug**
2023-08-14 12:15:01,522 - JsonScanner - ERROR - Traceback (most recent call last):
  File "/root/anaconda3/envs/federated_architecture/lib/python3.9/site-packages/nvflare/fuel/utils/class_utils.py", line 54, in instantiate_class
    instance = c(**init_params)
TypeError: Can't instantiate abstract class FedXGBHistogramExecutor with abstract method load_data

**To Reproduce**
1. Go to NVFlare/examples/advanced/xgboost/histogram-based
2. run “bash run_experiment_simulator.sh” in terminal
3. See error
2023-08-14 12:15:01,522 - JsonScanner - ERROR - Traceback (most recent call last):
  File "/root/anaconda3/envs/federated_architecture/lib/python3.9/site-packages/nvflare/fuel/utils/class_utils.py", line 54, in instantiate_class
    instance = c(**init_params)
TypeError: Can't instantiate abstract class FedXGBHistogramExecutor with abstract method load_data

**Expected behavior**
Run this example normally

**Desktop (please complete the following information):**
 - OS: [ Linux 4.4.0-72-generic]
 - Python Version [3.9.16 Anaconda]
 - NVFlare Version [2.3.2

**Additional context**
none

**Comment by SYangster** [comment]
Hi, thank you for bringing this to our attention. It seems that the newest changes to the XGBoost examples did not make it into the latest NVFlare 2.3.2 release. Could you try uninstalling nvflare 2.3.2 from your virtual environment and doing `pip install -e .` from the root of the cloned NVFlare repo to get the latest changes for now? This should ensure that the NVFlare version works with the new examples.

**Comment by YuanTingHsieh** [comment]
@yizhihenpidehou thanks for raising the issue.

I see you are using NVFlare 2.3.2 version.
Please use the example codes in branch 2.3.
I just tried in on my Ubuntu machine and it is working.

After our branch renaming, our MAIN branch is now the latest branch that contains newest features that might not be fully tested.
If you want to use latest features you can follow what @SYangster said.
Checkout the main branch and do `pip install -e .`

Otherwise, please use the example in the branch that matches the NVFlare version you are using.

**Comment by yizhihenpidehou** [comment]
Thank you for the kind help, it seems to work on my Ubuntu machine!!! ：）
