### ISSUE TITLE
support YAML for configs

### ISSUE THREAD

**Issue by Nintorac** [NVIDIA/NVFlare#198]
As YAML is a superset of JSON this should be fairly easy to do without any major code modifications.

Yaml is nice as it allows some fun things like:
- inline commenting 
-  human readability
- env var substitution

**Comment by chesterxgchen** [comment]
@Nintorac  what do you think of HOCON ? for python there is pyhocon (https://github.com/chimpler/pyhocon). It supports 
*Include
*variable substitution 
*Inheritance
*overwrite 
* inline and block comments
*it can easily convert to Json, YAML, java properties 
* has both python and Java supports
*

**Comment by Nintorac** [comment]
Hmm, yes HOCON does look good, not something I have come across before.

I would be a little hesitant though as (IMO) the devops industry seems to be moving towards using YAML as a standard configuration markup and YAML does also provide all the mentioned features

**Comment by chesterxgchen** [comment]
Understand. The HOCON is originally from Java/Scala world. For example Spark uses HOCON in lightbend config ( also called typesafe config, the company changed name from typesafe to lightbend). I think the team also created pyhocon afterwards.  But the industry (especially K8s and others) seem moving towards YAML, even though may not be as good as HOCON (IMHO).  But I just like to see what others think on this.

**Comment by taleinat** [comment]
FWIW I advise against supporting YAML in thise case, it has many surprising "sharp edges" that make it a poor for non-experts in my opinion. One example, "yes" and "no" are parsed as boolean true and false, rather than strings. Another example: "1.2" is a number, but "1.2.3" is a string, so one must always be extra-careful with version number. JSON has none of these issues.

If you were to consider supporting additional language for config, take a look at TOML, which is *much* simpler than YAML and is specifically geared toward human-edited config files. For example, it supports comments and date-time values, which are sorely missing from JSON when used for configuration.

**Comment by YuanTingHsieh** [comment]
@Nintorac and @taleinat thanks for your feedbacks!

@chesterxgchen recently added support for alternative config formats.

Added PyHOCON and OmegaConf as example reference.

(https://github.com/NVIDIA/NVFlare/pull/1796 https://github.com/NVIDIA/NVFlare/pull/1816 https://github.com/NVIDIA/NVFlare/pull/1824)

Users can now use their own preferable config format other than just "JSON".
