### ISSUE TITLE
[BUG] CIFAR-10 real-world example fails to run without GPU

### ISSUE THREAD

**Issue by taleinat** [NVIDIA/NVFlare#2002]
**Describe the bug**
The example found at `examples/advanced/cifar10/cifar10-real-world/` fails to run on a single machine without a GPU.

**To Reproduce**
Follow the instructions in the README:

1. Install requirements
2. Download the CIFAR-10 dataset
3. Create your FL workspace and start FL system: Only steps 3.1 and 3.3. From step 3.2, I tried both setting `N_GPU=0` and not setting it, but neither option worked.
4. Run automated experiments: Only step 4.3: `./submit_job.sh cifar10_fedavg_he 1.0`

**Expected behavior**
I expected the CIFAR-10 example to run some model training.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version 3.9
 - NVFlare Version 2.3.3

**Additional context**
The issue appears to be some component trying and failing to find a GPU, despite none being available on the system, and the default configuration appearing to specify that no GPUs are to be used.

**Comment by taleinat** [comment]
I will also mention that the `shutdown_fl_run.sh` script included with the example no longer works, which makes it difficult to stop the server and clients.

**Comment by taleinat** [comment]
I will also mention that having "min_clients" set to 8 in both `meta.json` and `config_fed_server.json` is confusing; is that intentional?

**Comment by YuanTingHsieh** [comment]
Hello @taleinat ,

What you observe is correct, NVFlare will use the information provided in a job's "meta.json" file to determine whether this job can be scheduled/deployed or not.

If you want to run this example WITHOUT GPU please modify the "meta.json"(https://github.com/NVIDIA/NVFlare/blob/main/examples/advanced/cifar10/cifar10-real-world/jobs/cifar10_fedavg_he/meta.json):

```
{
    "name": "cifar10_fedavg_he",
    "resource_spec": {},
    "deploy_map": {
        "cifar10_fedavg_he": [
            "@ALL"
        ]
    },
    "min_clients": 8
}
```

Noticed that this change remove all the GPU related requirements in resource_spec.
If they are specified, NVFlare will check if each site has the required resource for this job.



> I will also mention that the `shutdown_fl_run.sh` script included with the example no longer works, which makes it difficult to stop the server and clients.

This is a bug, I will submit a PR to fix this.


> I will also mention that having "min_clients" set to 8 in both `meta.json` and `config_fed_server.json` is confusing; is that intentional?

Yes, this is intentional as they serve different purposes.
- In "meta.json", it specifies the JOB's requirement for deployment.
  The "min_clients" here means that the JOB needs at least this number of sites to be up and running.
 
V.S.

- The "min_clients" variable used inside the "config_fed_server.json" is for ScatterAndGather workflow. (https://github.com/NVIDIA/NVFlare/blob/main/examples/advanced/cifar10/cifar10-real-world/jobs/cifar10_fedavg_he/cifar10_fedavg_he/config/config_fed_server.json#L77)
  This means that the SAG workflow will require this number of clients to respond for it to advance to the next round.


An example, we could specify the "min_clients" in meta.json as 8.
And specify the "min_clients" in config_fed_server.json as 4.

This means this job needs 8 sites to be up and running for it to be deployed/started.
But at each round, we need only 4 replies for us to move on to next round of aggregation/training.

**Comment by taleinat** [comment]
> Noticed that this change remove all the GPU related requirements in resource_spec.
If they are specified, NVFlare will check if each site has the required resource for this job.

Thanks for this clarification, @YuanTingHsieh!

That is not currently very clear from the documentation, so perhaps consider improving the docs in this regard.
