### ISSUE TITLE
Upload Issue

### ISSUE THREAD

**Issue by Nintorac** [NVIDIA/NVFlare#203]
Hi,

I am trying to develop a federated learning application and am running into an issue.

Steps to reproduce.

1. Follow the steps [here](https://nvidia.github.io/NVFlare/quickstart.html)
2. Follow the steps [here](https://github.com/NVIDIA/NVFlare/blob/3d15817c163140ea7f0618301dd9424c59478c8d/examples/hello-tf2/README.md)
3. Make some changes in `admin/transfer/hello-tf2`
4. In the admin client run `upload_app hello-tf2`
5. Check changes made in `admin` are reflected in `server` but they are not.

Similarly, making the changes directly in `server` and running `deploy_app hello-tf2 all` has no effect.

Maybe I am missing something obvious, any hints appreciated!

Thanks :)

As an aside, are there any community chat rooms available for the project?

**Comment by yhwen** [comment]
Hi Nintorac,

In the current version of NVFlare, if the changes you made in server is within the same Python class, the next "run" may not pick up your latest changes due to a Python class loading issue. If you issue a "restart server" admin command, then the server is able to pick up the new codes. On the client side, you won't have this issue, because FL client execution is using a different mechanism.

This issue will be addressed in the NVFlare next version.

**Comment by Nintorac** [comment]
Hi Yhwen,

Thanks for getting back to me. As I understand from what you are saying that the server needs to be restarted to incorporate code changes. I don't think that is related to the issue I am having though. I am looking for the changes in the file systems of servers and clients after `upload/deploy` but not seeing my changes being propogated in the filesysteem.
