### ISSUE TITLE
Admin CLI inconsistent parameter ordering

### ISSUE THREAD

**Issue by Nintorac** [NVIDIA/NVFlare#251]
~~Inconsistent parameter ordering between `deploy_app` and `start_app`~~ not sure why I was thinking `start_app` needs the app name, it doesn't. Should something like `start_app all sepsis` raise an error?

eg
```
> deploy_app sepsis all
> start_app all sepsis
```

**Comment by YuanTingHsieh** [comment]
Yeah, the start_app command does not require the app name, since our assumption is only one APP is running.

In the next release, we will try to support multiple "RUN" or "APP" at the same time.
If that is finished, I think this command will change so that the users need to specify what app to start.

We could print out some warning messages if the command is not used correctly.

@nvkevlu @nvidianz what do you think?

**Comment by yanchengnv** [comment]
Yes, in next version, the app deploy/start process will change to be automatic based on system-wide resources; and multiple jobs could be run at the same time if resources allow. Since it won't be too long before this version, we may not want to spend too much time on the commands that will be obsolete.

**Comment by YuanTingHsieh** [comment]
We will not fix this just for the start / deploy command since they will be changed / updated in next release.

If the user provides more arguments than needed, we might consider show some error / warning messages, I open an issue to track that: https://github.com/NVIDIA/NVFlare/issues/257
