### ISSUE TITLE
Client is very opinionated about actual GPU memory 

### ISSUE THREAD

**Issue by dirkpetersen** [NVIDIA/NVFlare#2559]
I start up a client that has a T4 GPU (g4dn.xlarge aws instance) and I told the dashboard it has 16GB ,but when I launch the client it is very opinionated: Well actually I am saying the GPU has 16384 MB when it really has only 15360 MB. Perhaps this could be handled a bit more gracefully, since even Nvidia is selling these GPU as 16GB 

/var/tmp/cloud/startup/start.sh

```
Error processing config ['/var/tmp/cloud/startup/../startup/fed_client.json', '/var/tmp/cloud/startup/../local/resources.json.default']: ConfigError: Error processing '/var/tmp/cloud/startup/../startup/fed_client.json' in element '{"id": "resource_manager", "path": "nvflare.app_common.resource_managers.gpu_resource_manager.GPUResourceManager", "args": {"num_of_gpus": 1, "mem_per_gpu_in_GiB": 16}}': path: 'components.#1', exception: 'ValueError: Memory per GPU specified (16384) exceeds available GPU memory: 15360.'
ConfigError: ConfigError: Error processing '/var/tmp/cloud/startup/../startup/fed_client.json' in element '{"id": "resource_manager", "path": "nvflare.app_common.resource_managers.gpu_resource_manager.GPUResourceManager", "args": {"num_of_gpus": 1, "mem_per_gpu_in_GiB": 16}}': path: 'components.#1', exception: 'ValueError: Memory per GPU specified (16384) exceeds available GPU memory: 15360.'
2024-05-06 05:10:50,439 - MPM - INFO - MPM: Good Bye!
```

**Comment by YuanTingHsieh** [comment]
Hi @dirkpetersen thanks for the issue!

Our default implementation of GPUResourceManager is this: https://github.com/NVIDIA/NVFlare/blob/main/nvflare/app_common/resource_managers/gpu_resource_manager.py#L43

So in your case you can specify 15 instead of 16.


This implementation is opinionated that only takes in memory in GB and it will multiply it by 1024 https://github.com/NVIDIA/NVFlare/blob/main/nvflare/app_common/resource_managers/gpu_resource_manager.py#L72

But you can refer to the code and write your own ResourceManager that is design for your specific needs.

After the dashboard generates the provision kits, you can go inside and edit each client site's "resource.json" file, for example:

```
{
  "format_version": 2,
  "client": {
    "retry_timeout": 30,
    "compression": "Gzip"
  },
  "components": [
    {
      "id": "resource_manager",
      "path": "path_to_your_code.MyGPUResourceManager",
      "args": {
        "num_of_gpus": 0,
        "mem_per_gpu_in_GiB": 0
      }
    },
    {
      "id": "resource_consumer",
      "path": "nvflare.app_common.resource_consumers.gpu_resource_consumer.GPUResourceConsumer",
      "args": {}
    }
  ]
}
```

**Comment by dirkpetersen** [comment]
Thank you, I did make this adjustment and it is explained in the documentation. I just submitted this to help improving usability of nvflare as most user would run into this issue at first

**Comment by YuanTingHsieh** [comment]
Got it, thanks for sharing your experience!
