### ISSUE TITLE
Give option to rename the application folder during upload

### ISSUE THREAD

**Issue by holgerroth** [NVIDIA/NVFlare#269]
Current `upload_app` command keeps the same folder name for the uploaded app. It could be useful to give an option to rename the app folder when uploading. This makes it easier to create different configurations without having to produce local copies on the admin's machine.

Current command usage:
```
> ? upload_app 
Client Commands
---------------
Command: file_transfer.upload_app
Description: upload application to the server
Usage: upload_app application_folder
```

Proposed command usage:
```
> ? upload_app 
Client Commands
---------------
Command: file_transfer.upload_app
Description: upload application to the server
Usage: upload_app application_folder (optional: destination_application_folder)
```

**Comment by yanchengnv** [comment]
This will change in 2.1. The uploaded job will be saved to Job Store and a Job ID will be returned. The Job Store could be a file system or S3 bucket, but won't be available to the end users.

**Comment by Nintorac** [comment]
I think this relates to #259

I'm still not clear on the distinction between a run and an app and can't find docs on the matter

Is it currently a 1-1 relationship or 1-n where n is a number of apps?

How will runs, app and jobs relate in the 2.1 release?

**Comment by YuanTingHsieh** [comment]
Hi @Nintorac ,

For the current 2.0 system:

- An "app" (contains required configs) define the components and workflows that it need to be run.

- A "RUN" can be think of as an experiment, so run_1 -> experiment_1, run_2 -> experiment_2.

- We requires user to set_run_number and upload / deploy the app to each site

Currently, we only support 1 app in each RUN (or we could say each experiment).
After RUN is finished, all the data / config / results related to this RUN is saved inside the run_XXX folder on each site.

So, come to the question, currently each RUN can only run 1 app.
And now we only run 1 RUN (or 1 experiment) at a time.

--------------------------------------------------------------------------------------

For the 2.1 release:

- An "app" is still the same concept as in 2.0
- A new and broader concept "Job" will be introduced.
  A job would contains a "deploy" concept which specifies what apps will be deployed on each site.
  For example: `"deploy": {"app_1": ["site_1", "site_2"], "app_2": ["site_2"]}`
- Users will submit Job into NVFlare, and the scheduler would find feasible Job to be run.
   No need to manually deploy app to each site anymore, as we will base on the "deploy" of job to do that
- A "RUN" would still mean an experiment, but we will not let user create / delete RUN folder on there own.
  We will create those folders in the back. Users would be getting Job ID so that they can get their results using that.

So each Job can has multiple different apps.
And we plan to support running multiple Jobs (or RUNs) at the same time if resources permitted.
  
 
@yanchengnv can correct me if things are wrong

Thanks

**Comment by Nintorac** [comment]
Ok thanks for the explanation, so I don't understand why the app is tied to the configuration?

When I think run I think a different configuration of my application, this is how it is used in eg. [SigOpt](https://app.sigopt.com/docs/experiments/intro), Weights and Biases, [Ray Tune](https://docs.ray.io/en/ray-0.4.0/tune.html) etc.

**Comment by chesterxgchen** [comment]
@nvidianz can you handle this

**Comment by chesterxgchen** [comment]
@Nintorac unless you miss-understood your comment, I think you might thinking different things. The examples you gave are ML experimentations, related to each run. Here @yanchengnv  and others were discussing the configuration needed to deploy apps. Unless non-federated app, where app only run in one site. federated ML app needs to configured so that system to know which site the app need to deployed and run. 

The original discussion were around upload app. This will be changed in next release to submit_job. I am closing this issue.
