### ISSUE TITLE
When I run the start.sh from poc/server/

### ISSUE THREAD

**Issue by holiday01** [NVIDIA/NVFlare#553]
start fl because of no pid.fl
new pid 18071
The following files are not secure content.
fed_server.json
start fl because process of 18071 does not exist
new pid 18081
The following files are not secure content.
fed_server.json
start fl because process of 18081 does not exist
new pid 18092
The following files are not secure content.
fed_server.json
start fl because process of 18092 does not exist
new pid 18102
The following files are not secure content.
fed_server.json
start fl because process of 18102 does not exist
new pid 18111
The following files are not secure content.
fed_server.json
start fl because process of 18111 does not exist
System is in trouble and unable to start the task!!!!!

**Comment by chesterxgchen** [comment]
thanks for raise the issue, probably you can help us by giving us a bit context. 
for example, 
python version, OS, what are the steps you have performed before you starting to see the errors.

**Comment by nvkevlu** [comment]
It seems like you edited the fed_server.json file manually after it was created by the provisioning process. This file is considered secure content and is signed, so it cannot be changed after provisioning or the signature verification will fail.

In order to change the preset values in fed_server.json, it may be necessary to alter nvflare/lighter/impl/master_template.yml near line 100 before running provision with your edited version of the code (may need to make sure PYTHONPATH points to the location of where you checked out the NVFlare repository).

**Comment by chesterxgchen** [comment]
also, make sure you are using python 3.8.

**Comment by holiday01** [comment]
It was done. I opened a new VM and worked. Thank you.

**Comment by chesterxgchen** [comment]
great. Close the issue
