### ISSUE TITLE
Docker.sh Admin

### ISSUE THREAD

**Issue by ajulyav** [NVIDIA/NVFlare#995]
When I try running any admin docker.sh after provisioning .yml file (i.e. admin@nvidia.com as it is given in the example), I wonder why by default this docker.sh for admin does not contain  --ipc=host $NETARG in docker run line ? I tried to run without this line, but then admin cannot connect to the server. So, I should modify this docker.sh manually and add this then.

So, what could be a reason why for all admins by default this is not like this, though for any client docker.sh is OK?

**To Reproduce**
1. Provision any .yml file with docker
2. Run server, client dockers and follow the basic start/connection procedure 
3. Run admin docker.sh built by default
4. Try to connect admin to the server and it is failed

**Expected behavior**
I expect that admin docker.sh should include --ipc=host $NETARG by default 

**Screenshots**
Screenshots can be added on request

**Desktop (please complete the following information):**
 - NVFlare Version 2.0

**Comment by IsaacYangSLA** [comment]
@ajulyav , can you share the /etc/hosts files from both the container and your host?  And can you check if you can, inside the admin container, resolve the IP address of the server?  This type of connection failure is often caused by the network configuration.  Admin console has to run in an environment that is able to resolve server's IP address, either by DNS or /etc/hosts.
